apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
